using Plots, SNN; plotly()
include("../examples/chain.jl")
include("../examples/hh_net.jl")
include("../examples/hh_neuron.jl")
include("../examples/if_net.jl")
include("../examples/if_neuron.jl")
include("../examples/iz_net.jl")
include("../examples/iz_neuron.jl")
include("../examples/oja.jl")
include("../examples/rate_net.jl")
include("../examples/stdp_demo.jl")
include("../examples/stdp_song.jl")
