version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: /root/project/RoecketScience   # Clone into a directory whose name matches your Package.

    #working_directory: /root/project/SpikingNeuralNetworks   # Clone into a directory whose name matches your Package.
    docker:
        - image: julia:1.1                # image comes from Docker hub
    steps:
        - checkout
        - run:
              name: Install and Test this package
              command: julia -e  'using Pkg; Pkg.update(); Pkg.clone(pwd()); Pkg.build("MyPkg"); Pkg.test("MyPkg", coverage=true);'
         - run:
              name: Process code-coverage
              command: julia -e 'using Pkg; cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; coverage = process_folder(); LCOV.writefile("coverage-lcov.info", coverage)'
          - run:
              command: julia -E '] dev .'
          - run:
              command: julia test/runtests.jl
