# .circleci/config.yml
version: 2.1
jobs:
  build:
    working_directory: /root/project/SpikingNeuralNetworks   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.5                # image comes from Docker hub
    steps:
      - checkout
      - run:
          name: Install and Test this package
          command: julia -e 'using Pkg; Pkg.update(); pkg"dev ."; Pkg.test("SpikingNeuralNetworks", coverage=true);'
      - run:
          name: "run tests"
          command: julia test/runtests.jl
      - run:
          name: Process code-coverage
          command: julia -e 'using Pkg; cd(Pkg.dir("SpikingNeuralNetworks")); Pkg.add("Coverage"); using Coverage; coverage = process_folder(); LCOV.writefile("coverage-lcov.info", coverage)'
